#!/bin/bash
# Created by the VLSCI job script generator
# Sun Oct 26 2014 17:23:48 GMT+1100 (AEDT)

# The name of the job:
#SBATCH --job-name="Zombie-Project"

# Number of BlueGene compute nodes used by the job (multiply by 16 to get CPU cores):
#SBATCH --nodes=2

# The maximum running time of the job in days-hours:mins
#SBATCH --time=0-1:0

# The job command(s):
srun --ntasks=2 --ntasks-per-node=1 ./Zombie